// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportReg(arg1) {
  return window['go']['main']['App']['ExportReg'](arg1);
}

export function GetGameFile() {
  return window['go']['main']['App']['GetGameFile']();
}

export function GetRegs() {
  return window['go']['main']['App']['GetRegs']();
}

export function ImportReg(arg1) {
  return window['go']['main']['App']['ImportReg'](arg1);
}

export function SelectGameFile() {
  return window['go']['main']['App']['SelectGameFile']();
}

export function StartGame() {
  return window['go']['main']['App']['StartGame']();
}

export function StartGis(arg1) {
  return window['go']['main']['App']['StartGis'](arg1);
}
