// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportReg(arg1:string):Promise<void>;

export function GetGameFile():Promise<string>;

export function GetRegs():Promise<Array<string>>;

export function ImportReg(arg1:string):Promise<void>;

export function SelectGameFile():Promise<boolean>;

export function StartGame():Promise<void>;

export function StartGis(arg1:string):Promise<void>;
