name: pre-release

on: 
    push:
        branches:
          - main
        tags:
            - "v*"
jobs:
    prelease:
        name: "pre release"
        runs-on: windows-latest

        steps:
            - name: "checkout"
              uses: actions/checkout@v4

            - name: "set up node"
              uses: actions/setup-node@v2
              with:
                node-version: "21.x"
            - run: corepack enable pnpm

            - name: "setup golang"
              uses: actions/setup-go@v5
              with:
                go-version-file: "go.mod"

            - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
            - name: build
              run: wails build

            - name: install upx
              uses: svenstaro/upx-action@v2
              with:
                files: build/bin/genshin-switch.exe


            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "latest"
                prerelease: true
                files: |
                    build/bin/genshin-switch.exe









